version: "3.3"

services:
  database:
    image: database
    environment:
      MYSQL_ROOT_PASSWORD: DockerCon!!!
    ports:
      - "3306:3306"
    networks:
      - back-tier
  
  java-app:
    image: java-app
    environment:
      BASEURI: "http://dotnet-api/api/users"
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier

  dotnet-api:
    image: dotnet-api
    ports:
      - "57989:80"
    networks:
      - front-tier
      - back-tier

networks:
  back-tier:
  front-tier:
