version: "3.3"

services:

  database:
    image: dockersamples/hybrid-app-db
    networks:
      - back-tier

  java-app:
    image: dockersamples/hybrid-app-web
    networks:
      - front-tier
      - back-tier

  netfx-api:
    image: dockersamples/hybrid-app-api:netfx
    networks:
      - back-tier

networks:
  back-tier:
  front-tier: